apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: docker-web-app
        image: docker_web_app:0.0.2.RELEASE
        ports:
        - containerPort: 80
